name: Test setup-with-retry
concurrency:
  group: selfdrive-tests-ci-run-${{ inputs.run_number }}-${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  PYTHONWARNINGS: error
  BASE_IMAGE: openpilot-base
  AZURE_TOKEN: ${{ secrets.AZURE_COMMADATACI_OPENPILOTCI_TOKEN }}

  DOCKER_LOGIN: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  BUILD: selfdrive/test/docker_build.sh base

  RUN: docker run --shm-size 2G -v $PWD:/tmp/openpilot -w /tmp/openpilot -e CI=1 -e PYTHONWARNINGS=error -e FILEREADER_CACHE=1 -e PYTHONPATH=/tmp/openpilot -e NUM_JOBS -e JOB_ID -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -v $GITHUB_WORKSPACE/.ci_cache/scons_cache:/tmp/scons_cache -v $GITHUB_WORKSPACE/.ci_cache/comma_download_cache:/tmp/comma_download_cache -v $GITHUB_WORKSPACE/.ci_cache/openpilot_cache:/tmp/openpilot_cache $BASE_IMAGE /bin/bash -c

  PYTEST: pytest --continue-on-collection-errors --cov --cov-report=xml --cov-append --durations=0 --durations-min=5 --hypothesis-seed 0 -n logical

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  uv_play:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Define a custom uv cache path
      uses: astral-sh/setup-uv@v5
      with:
          enable-cache: true
          cache-local-path: "/tmp/uvcache"
    - name: install ubuntu packages
      shell: bash
      run: |
        sudo apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        alien \
        unzip \
        tar \
        curl \
        xz-utils \
        dbus \
        gcc-arm-none-eabi \
        tmux \
        vim \
        libx11-6 \
        wget \
        ca-certificates \
        clang \
        build-essential \
        gcc-arm-none-eabi \
        liblzma-dev \
        capnproto \
        libcapnp-dev \
        curl \
        libcurl4-openssl-dev \
        git \
        git-lfs \
        ffmpeg \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libavfilter-dev \
        libbz2-dev \
        libeigen3-dev \
        libffi-dev \
        libglew-dev \
        libgles2-mesa-dev \
        libglfw3-dev \
        libglib2.0-0 \
        libjpeg-dev \
        libqt5charts5-dev \
        libncurses5-dev \
        libssl-dev \
        libusb-1.0-0-dev \
        libzmq3-dev \
        libzstd-dev \
        libsqlite3-dev \
        libsystemd-dev \
        locales \
        opencl-headers \
        ocl-icd-libopencl1 \
        ocl-icd-opencl-dev \
        portaudio19-dev \
        qttools5-dev-tools \
        libqt5svg5-dev \
        libqt5serialbus5-dev  \
        libqt5x11extras5-dev \
        libqt5opengl5-dev \
        && sudo rm -rf /var/lib/apt/lists/*


    - name: Install dependencies
      shell: bash
      run: |
        echo "installing python packages..."
        uv sync --frozen --all-extras
        source .venv/bin/activate
  uv_play2:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Restore uv cache
        uses: actions/cache@v3
        with:
                path: /tmp/uvcache
                key: ${{ runner.os }}-node-${{ hashFiles('pyproject.toml') }}
                restore-keys: |
                  ${{ runner.os }}-node-
      - name: Define a custom uv cache path
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: false
            cache-local-path: "/tmp/uvcache"
      - name: Install dependencies
        shell: bash
        run: |
          echo "installing python packages..."
          uv sync --frozen --all-extras
          source .venv/bin/activate


  build:
    runs-on:
      - ${{ ((github.repository == 'commaai/openpilot') && ((github.event_name != 'pull_request') || (github.event.pull_request.head.repo.full_name == 'commaai/openpilot'))) && 'namespace-profile-amd64-8x16' || 'ubuntu-24.04' }}
      - ${{ ((github.repository == 'commaai/openpilot') && ((github.event_name != 'pull_request') || (github.event.pull_request.head.repo.full_name == 'commaai/openpilot'))) && 'namespace-experiments:docker.builds.local-cache=separate' || 'ubuntu-24.04' }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup docker push
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'commaai/openpilot'
      run: |
        echo "PUSH_IMAGE=true" >> "$GITHUB_ENV"
        $DOCKER_LOGIN
    - uses: ./.github/workflows/setup-with-retry
